package Formularios;

import java.awt.Event;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karen Benedetti M
 */
public class FrmEstudiante extends javax.swing.JFrame {

    ArrayList<Estudiante> listaEstudiantes = new ArrayList<>();
    DefaultListModel modeloEstudiante;
    DefaultTableModel modeloTablaEstudiante;

    /**
     * Creates new form FrmEstudiante
     */
    public FrmEstudiante() {
        initComponents();
        setLocationRelativeTo(null);
        crearModeloTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGenero = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        chkIngles = new javax.swing.JCheckBox();
        chkProgramacion = new javax.swing.JCheckBox();
        chkCoaching = new javax.swing.JCheckBox();
        cmbCiclo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEstudiantes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEstudiante = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Identificación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 100, 43);

        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdentificacion);
        txtIdentificacion.setBounds(168, 60, 245, 43);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(170, 120, 240, 40);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 80, 40);

        jLabel3.setText("Genero");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 60, 40);

        btgGenero.add(rbMasculino);
        rbMasculino.setText("Masculino");
        getContentPane().add(rbMasculino);
        rbMasculino.setBounds(170, 190, 110, 29);

        btgGenero.add(rbFemenino);
        rbFemenino.setText("Femenino");
        getContentPane().add(rbFemenino);
        rbFemenino.setBounds(310, 190, 101, 29);

        chkIngles.setText("Inglés");
        getContentPane().add(chkIngles);
        chkIngles.setBounds(60, 260, 75, 29);

        chkProgramacion.setText("Programación");
        chkProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProgramacionActionPerformed(evt);
            }
        });
        getContentPane().add(chkProgramacion);
        chkProgramacion.setBounds(160, 260, 140, 29);

        chkCoaching.setText("Coaching");
        getContentPane().add(chkCoaching);
        chkCoaching.setBounds(310, 260, 97, 29);

        cmbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Python", "Java", "Web" }));
        getContentPane().add(cmbCiclo);
        cmbCiclo.setBounds(200, 310, 200, 40);

        jLabel4.setText("Ciclo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 310, 60, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(70, 20, 130, 50);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(70, 130, 130, 40);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar);
        btnLimpiar.setBounds(70, 80, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(470, 60, 260, 190);

        lstEstudiantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado estudiantes"));
        jScrollPane1.setViewportView(lstEstudiantes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 380, 360, 140);

        tblEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblEstudianteKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblEstudiante);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(472, 280, 420, 240);

        setBounds(0, 0, 955, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void chkProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProgramacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProgramacionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Estudiante estudiante = new Estudiante();
        modeloEstudiante = new DefaultListModel();
        String materias = "";
        estudiante.setId(Integer.parseInt(txtIdentificacion.getText()));
        estudiante.setNombre(txtNombre.getText());
        estudiante.setGenero(rbFemenino.isSelected() ? "Femenino" : "Masculino");
        if (chkIngles.isSelected()) {

            materias = "Inglés";
        }

        if (chkCoaching.isSelected()) {
            materias += "Coaching";
        }

        if (chkProgramacion.isSelected()) {
            materias += "Programacion";
        }

        estudiante.setMateria(materias);
        estudiante.setCiclo(cmbCiclo.getSelectedItem().toString());
        listaEstudiantes.add(estudiante);
        JOptionPane.showMessageDialog(this, "Estudiante guardado con exito!");
        for (Estudiante estudianteRecorrido : listaEstudiantes) {
            modeloEstudiante.addElement(estudiante.getNombre());
        }
        lstEstudiantes.setModel(modeloEstudiante);

        modeloTablaEstudiante.setRowCount(0);
        for (Estudiante estudianteRecorrer : listaEstudiantes) {
            String[] datos = {Integer.toString(estudianteRecorrer.getId()), estudianteRecorrer.getNombre()};
            modeloTablaEstudiante.addRow(datos);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdentificacion.setText("");
        txtNombre.setText("");
        btgGenero.clearSelection();
        chkIngles.setSelected(false);
        chkCoaching.setSelected(false);
        chkProgramacion.setSelected(false);
        cmbCiclo.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEstudianteKeyReleased
        if (evt.getKeyCode() == Event.ENTER) {
            int fila = tblEstudiante.getSelectedRow();
            int idABuscar = Integer.parseInt(tblEstudiante.getValueAt(fila, 0).toString());
            int j = 0;
            for (Estudiante estudianteRecorrido : listaEstudiantes) {
                if (estudianteRecorrido.getId() == idABuscar) {
                    estudianteRecorrido.setNombre(tblEstudiante.getValueAt(fila, 1).toString());
                    listaEstudiantes.set(j, estudianteRecorrido);
                }
                j++;
            }
        }
    }//GEN-LAST:event_tblEstudianteKeyReleased

    private void crearModeloTabla() {
        String[] cabeceraTabla = {"Identificacion", "Nombre"};
        modeloTablaEstudiante = new DefaultTableModel(null, cabeceraTabla);
        tblEstudiante.setModel(modeloTablaEstudiante);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGenero;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkCoaching;
    private javax.swing.JCheckBox chkIngles;
    private javax.swing.JCheckBox chkProgramacion;
    private javax.swing.JComboBox<String> cmbCiclo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lstEstudiantes;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tblEstudiante;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
