/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import modelo.Curso;
import modelo.Estudiante;
import static modelo.Estudiante.matricularEstudiante;

/**
 *
 * @author Karen Benedetti M
 */
public class MatricularEstudianteFrame extends javax.swing.JFrame {

    ArrayList<Curso> listaCursos = new ArrayList<>();
    ArrayList<Estudiante> listaEstudiantes = new ArrayList<>();
    ArrayList<Estudiante> listaEstudiantesSeleccionados = new ArrayList<>();

    /**
     * Creates new form MatricularEstudianteFrame
     */
    public MatricularEstudianteFrame() {
        initComponents();
        setLocationRelativeTo(null);
        llenarListaCursos();
        llenarListaEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMatricular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstEstudiantesSeleccionados = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEstudiantes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        btnMatricular.setBackground(new java.awt.Color(43, 137, 184));
        btnMatricular.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnMatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnMatricular.setText("Matricular");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(43, 137, 184));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Colegio.png"))); // NOI18N
        jLabel5.setText("Matricular estudainte");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );

        lstEstudiantesSeleccionados.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiantes a matricular"));
        lstEstudiantesSeleccionados.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lstEstudiantesSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEstudiantesSeleccionadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstEstudiantesSeleccionados);

        lstCursos.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lstCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursos);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel1.setText("Selecciona el curso para asignar estudiantes:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("CURSO SELECCIONADO:");

        lstEstudiantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiantes"));
        lstEstudiantes.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lstEstudiantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstEstudiantes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnMatricular)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 600, 610);

        setBounds(0, 0, 622, 656);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed

        for (Estudiante estudianteRecorrido : listaEstudiantesSeleccionados) {
            matricularEstudiante(estudianteRecorrido.getId(), Long.parseLong(jLabel2.getText()));
        }
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void lstCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCursosMouseClicked
        Curso cursoAEditar = new Curso();
        String num = lstCursos.getSelectedValue().split(":")[0];
        long numCurso = Long.parseLong(num);
        for (Curso cursoRecorrido : listaCursos) {
            if (cursoRecorrido.getId() == numCurso) {
                cursoAEditar = cursoRecorrido;
            }
        }
        jLabel2.setText(String.valueOf(cursoAEditar.getId()));
    }//GEN-LAST:event_lstCursosMouseClicked

    private void lstEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEstudiantesMouseClicked
        Estudiante estudianteSeleccionado = new Estudiante();
        String num = lstEstudiantes.getSelectedValue().split(":")[0];
        long numEstudiante = Long.parseLong(num);
        for (Estudiante estudianteRecorrido : listaEstudiantes) {
            if (estudianteRecorrido.getId() == numEstudiante) {
                estudianteSeleccionado = estudianteRecorrido;
            }
        }
        llenarListaEstudiantesSeleccionados(estudianteSeleccionado);
    }//GEN-LAST:event_lstEstudiantesMouseClicked

    private void lstEstudiantesSeleccionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEstudiantesSeleccionadosMouseClicked
        Estudiante estudianteSeleccionado = new Estudiante();
        String num = lstEstudiantesSeleccionados.getSelectedValue().split(":")[0];
        long numEstudiante = Long.parseLong(num);
        for (Estudiante estudianteRecorrido : listaEstudiantesSeleccionados) {
            if (estudianteRecorrido.getId() == numEstudiante) {
                estudianteSeleccionado = estudianteRecorrido;
            }
        }
        listaEstudiantesSeleccionados.remove(estudianteSeleccionado);
        llenarListaEstudiantesSeleccionados();
    }//GEN-LAST:event_lstEstudiantesSeleccionadosMouseClicked

    public void llenarListaCursos() {
        Curso curso = new Curso();
        listaCursos = curso.leer();
        DefaultListModel modeloLista = new DefaultListModel();
        for (Curso cursoRecorrido : listaCursos) {
            modeloLista.addElement(cursoRecorrido.getId() + ": " + cursoRecorrido.getNombre());
        }
        lstCursos.setModel(modeloLista);
    }

    public void llenarListaEstudiantes() {
        Estudiante estudiante = new Estudiante();
        listaEstudiantes = estudiante.leer();
        DefaultListModel modeloLista = new DefaultListModel();
        for (Estudiante estudianteRecorrido : listaEstudiantes) {
            modeloLista.addElement(estudianteRecorrido.getId() + ": " + estudianteRecorrido.getNombre());
        }
        lstEstudiantes.setModel(modeloLista);
    }

    public void llenarListaEstudiantesSeleccionados(Estudiante estudiante) {
        if (listaEstudiantesSeleccionados.contains(estudiante)) {

        } else {
            listaEstudiantesSeleccionados.add(estudiante);
            DefaultListModel modeloLista = new DefaultListModel();
            for (Estudiante estudianteRecorrido : listaEstudiantesSeleccionados) {
                modeloLista.addElement(estudianteRecorrido.getId() + ": " + estudianteRecorrido.getNombre());
            }
            lstEstudiantesSeleccionados.setModel(modeloLista);

        }
    }

    public void llenarListaEstudiantesSeleccionados() {
        DefaultListModel modeloLista = new DefaultListModel();
        for (Estudiante estudianteRecorrido : listaEstudiantesSeleccionados) {
            modeloLista.addElement(estudianteRecorrido.getId() + ": " + estudianteRecorrido.getNombre());
        }
        lstEstudiantesSeleccionados.setModel(modeloLista);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatricularEstudianteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatricular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstCursos;
    private javax.swing.JList<String> lstEstudiantes;
    private javax.swing.JList<String> lstEstudiantesSeleccionados;
    // End of variables declaration//GEN-END:variables
}
