/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import modelo.Curso;
import modelo.Estudiante;
import modelo.Profesor;

/**
 *
 * @author Karen Benedetti M
 */
public class Principal extends javax.swing.JFrame {

    ArrayList<Profesor> listaProfesores = new ArrayList<>();
    ArrayList<Estudiante> listaEstudiantes = new ArrayList<>();
    ArrayList<Curso> listaCursos = new ArrayList<>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        llenarListaProfesores();
        llenarListaEstudiantes();
        llenarListaCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProfesores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEstudiantes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCursos = new javax.swing.JList<>();
        btnAgregarProfesor = new javax.swing.JButton();
        btnAgregarCurso = new javax.swing.JButton();
        btnAgregarEstudiante = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCrearProfesor = new javax.swing.JMenuItem();
        mnListarInfoProfesor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCrearEstudiante = new javax.swing.JMenuItem();
        mnListarInforEstudiante = new javax.swing.JMenuItem();
        mnListarEstPorCurso = new javax.swing.JMenuItem();
        mnListarEstPorProf = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnCrearCurso = new javax.swing.JMenuItem();
        mnListarInfoCurso = new javax.swing.JMenuItem();
        mnAsigarProfesor = new javax.swing.JMenuItem();
        mnMatricularEstudiante = new javax.swing.JMenuItem();
        mnListarCursosDePrf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lstProfesores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstProfesores.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lstProfesores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProfesoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstProfesores);

        lstEstudiantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstEstudiantes.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lstEstudiantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstEstudiantes);

        lstCursos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstCursos.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lstCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCursosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstCursos);

        btnAgregarProfesor.setBackground(new java.awt.Color(43, 137, 184));
        btnAgregarProfesor.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnAgregarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar.png"))); // NOI18N
        btnAgregarProfesor.setText("Agregar");
        btnAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProfesorActionPerformed(evt);
            }
        });

        btnAgregarCurso.setBackground(new java.awt.Color(43, 137, 184));
        btnAgregarCurso.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnAgregarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar.png"))); // NOI18N
        btnAgregarCurso.setText("Agregar");
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        btnAgregarEstudiante.setBackground(new java.awt.Color(43, 137, 184));
        btnAgregarEstudiante.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        btnAgregarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar.png"))); // NOI18N
        btnAgregarEstudiante.setText("Agregar");
        btnAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstudianteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(43, 137, 184));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Colegio.png"))); // NOI18N
        jLabel4.setText("Colegio UNI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("ESTUDIANTES");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("CURSOS");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("PROFESORES");

        btnRefrescar.setBackground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setForeground(new java.awt.Color(43, 137, 184));
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Refrescar.png"))); // NOI18N
        btnRefrescar.setBorder(null);
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnAgregarProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarEstudiante)
                .addGap(111, 111, 111)
                .addComponent(btnAgregarCurso)
                .addGap(51, 51, 51))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProfesor)
                    .addComponent(btnAgregarCurso)
                    .addComponent(btnAgregarEstudiante))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 570);

        jMenuBar1.setBackground(new java.awt.Color(43, 137, 184));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(421, 31));

        jMenu1.setText("Profesor");

        mnCrearProfesor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnCrearProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar.png"))); // NOI18N
        mnCrearProfesor.setText("Crear");
        mnCrearProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearProfesorActionPerformed(evt);
            }
        });
        jMenu1.add(mnCrearProfesor);

        mnListarInfoProfesor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnListarInfoProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listar.png"))); // NOI18N
        mnListarInfoProfesor.setText("Listar informacion de profesores");
        mnListarInfoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarInfoProfesorActionPerformed(evt);
            }
        });
        jMenu1.add(mnListarInfoProfesor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Estudiante");

        mnCrearEstudiante.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnCrearEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar.png"))); // NOI18N
        mnCrearEstudiante.setText("Crear");
        mnCrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearEstudianteActionPerformed(evt);
            }
        });
        jMenu2.add(mnCrearEstudiante);

        mnListarInforEstudiante.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnListarInforEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listar.png"))); // NOI18N
        mnListarInforEstudiante.setText("Listar informacion de estudiantes");
        mnListarInforEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarInforEstudianteActionPerformed(evt);
            }
        });
        jMenu2.add(mnListarInforEstudiante);

        mnListarEstPorCurso.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnListarEstPorCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar.png"))); // NOI18N
        mnListarEstPorCurso.setText("Consultar estudiante por curso");
        mnListarEstPorCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarEstPorCursoActionPerformed(evt);
            }
        });
        jMenu2.add(mnListarEstPorCurso);

        mnListarEstPorProf.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnListarEstPorProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar.png"))); // NOI18N
        mnListarEstPorProf.setText("Consultar estudiante por profesor");
        mnListarEstPorProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarEstPorProfActionPerformed(evt);
            }
        });
        jMenu2.add(mnListarEstPorProf);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Curso");

        mnCrearCurso.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnCrearCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar.png"))); // NOI18N
        mnCrearCurso.setText("Crear");
        mnCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCrearCursoActionPerformed(evt);
            }
        });
        jMenu3.add(mnCrearCurso);

        mnListarInfoCurso.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnListarInfoCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listar.png"))); // NOI18N
        mnListarInfoCurso.setText("Listar informacion de cursos");
        mnListarInfoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarInfoCursoActionPerformed(evt);
            }
        });
        jMenu3.add(mnListarInfoCurso);

        mnAsigarProfesor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnAsigarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Asignar.png"))); // NOI18N
        mnAsigarProfesor.setText("Asignar profesor");
        mnAsigarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAsigarProfesorActionPerformed(evt);
            }
        });
        jMenu3.add(mnAsigarProfesor);

        mnMatricularEstudiante.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnMatricularEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AgregarEstudiante.png"))); // NOI18N
        mnMatricularEstudiante.setText("Matricular estudiante");
        mnMatricularEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMatricularEstudianteActionPerformed(evt);
            }
        });
        jMenu3.add(mnMatricularEstudiante);

        mnListarCursosDePrf.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mnListarCursosDePrf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listar.png"))); // NOI18N
        mnListarCursosDePrf.setText("Consultar cursos de un profesor");
        mnListarCursosDePrf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarCursosDePrfActionPerformed(evt);
            }
        });
        jMenu3.add(mnListarCursosDePrf);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 722, 656);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProfesorActionPerformed
        AgregarProfesorFrame ventanaAgregarProfesor = new AgregarProfesorFrame();
        ventanaAgregarProfesor.setVisible(true);
    }//GEN-LAST:event_btnAgregarProfesorActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        llenarListaProfesores();
        llenarListaEstudiantes();
        llenarListaCursos();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void lstProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProfesoresMouseClicked
        Profesor profesorAEditar = new Profesor();
        String num = lstProfesores.getSelectedValue().split(":")[0];
        long numProfesor = Long.parseLong(num);
        for (Profesor profesorRecorrido : listaProfesores) {
            if (profesorRecorrido.getId() == numProfesor) {
                profesorAEditar = profesorRecorrido;
            }
        }
        new ActualizarProfesorFrame(profesorAEditar).setVisible(true);
    }//GEN-LAST:event_lstProfesoresMouseClicked

    private void btnAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstudianteActionPerformed
        AgregarEstudianteFrame ventanaAgregarEstudiante = new AgregarEstudianteFrame();
        ventanaAgregarEstudiante.setVisible(true);
    }//GEN-LAST:event_btnAgregarEstudianteActionPerformed

    private void lstEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEstudiantesMouseClicked
        Estudiante estudianteAEditar = new Estudiante();
        String num = lstEstudiantes.getSelectedValue().split(":")[0];
        long numEstudiante = Long.parseLong(num);
        for (Estudiante estudianteRecorrido : listaEstudiantes) {
            if (estudianteRecorrido.getId() == numEstudiante) {
                estudianteAEditar = estudianteRecorrido;
            }
        }
        new ActualizarEstudianteFrame(estudianteAEditar).setVisible(true);
    }//GEN-LAST:event_lstEstudiantesMouseClicked

    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed
        AgregarCursoFrame ventanaAgregarCurso = new AgregarCursoFrame();
        ventanaAgregarCurso.setVisible(true);
    }//GEN-LAST:event_btnAgregarCursoActionPerformed

    private void lstCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCursosMouseClicked
        Curso cursoAEditar = new Curso();
        String num = lstCursos.getSelectedValue().split(":")[0];
        long numCurso = Long.parseLong(num);
        for (Curso cursoRecorrido : listaCursos) {
            if (cursoRecorrido.getId() == numCurso) {
                cursoAEditar = cursoRecorrido;
            }
        }
        new ActualizarCursoFrame(cursoAEditar).setVisible(true);
    }//GEN-LAST:event_lstCursosMouseClicked

    private void mnAsigarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAsigarProfesorActionPerformed
        AsignarProfesorFrame ventanaAsignarProfesor = new AsignarProfesorFrame();
        ventanaAsignarProfesor.setVisible(true);
    }//GEN-LAST:event_mnAsigarProfesorActionPerformed

    private void mnMatricularEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMatricularEstudianteActionPerformed
        MatricularEstudianteFrame ventanaMatricularEstudiante = new MatricularEstudianteFrame();
        ventanaMatricularEstudiante.setVisible(true);
    }//GEN-LAST:event_mnMatricularEstudianteActionPerformed

    private void mnCrearProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearProfesorActionPerformed
        AgregarProfesorFrame ventanaAgregarProfesor = new AgregarProfesorFrame();
        ventanaAgregarProfesor.setVisible(true);
    }//GEN-LAST:event_mnCrearProfesorActionPerformed

    private void mnCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearEstudianteActionPerformed
        AgregarEstudianteFrame ventanaAgregarEstudiante = new AgregarEstudianteFrame();
        ventanaAgregarEstudiante.setVisible(true);
    }//GEN-LAST:event_mnCrearEstudianteActionPerformed

    private void mnCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCrearCursoActionPerformed
        AgregarCursoFrame ventanaAgregarCurso = new AgregarCursoFrame();
        ventanaAgregarCurso.setVisible(true);
    }//GEN-LAST:event_mnCrearCursoActionPerformed

    private void mnListarCursosDePrfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarCursosDePrfActionPerformed
        ListarCursosPorProfFrame ventanaListarCursoProf = new ListarCursosPorProfFrame();
        ventanaListarCursoProf.setVisible(true);
    }//GEN-LAST:event_mnListarCursosDePrfActionPerformed

    private void mnListarEstPorProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarEstPorProfActionPerformed
        ListarEstudiantesPorProfFrame ventanaListarEstudianteProf = new ListarEstudiantesPorProfFrame();
        ventanaListarEstudianteProf.setVisible(true);
    }//GEN-LAST:event_mnListarEstPorProfActionPerformed

    private void mnListarEstPorCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarEstPorCursoActionPerformed
        ListarEstudiantesPorCursoFrame ventanaListarEstudianteCurso = new ListarEstudiantesPorCursoFrame();
        ventanaListarEstudianteCurso.setVisible(true);
    }//GEN-LAST:event_mnListarEstPorCursoActionPerformed

    private void mnListarInfoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarInfoProfesorActionPerformed
        ListarProfesoresFrame ventanaListarProfesores = new ListarProfesoresFrame();
        ventanaListarProfesores.setVisible(true);
    }//GEN-LAST:event_mnListarInfoProfesorActionPerformed

    private void mnListarInforEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarInforEstudianteActionPerformed
        ListarEstudiantesFrame ventanaListarEstudiantes = new ListarEstudiantesFrame();
        ventanaListarEstudiantes.setVisible(true);
    }//GEN-LAST:event_mnListarInforEstudianteActionPerformed

    private void mnListarInfoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarInfoCursoActionPerformed
        ListarCursosFrame ventanaListarCursos = new ListarCursosFrame();
        ventanaListarCursos.setVisible(true);
    }//GEN-LAST:event_mnListarInfoCursoActionPerformed

    public void llenarListaProfesores() {
        Profesor profesor = new Profesor();
        listaProfesores = profesor.leer();
        DefaultListModel modeloLista = new DefaultListModel();
        for (Profesor profesorRecorrido : listaProfesores) {
            modeloLista.addElement(profesorRecorrido.getId() + ": " + profesorRecorrido.getNombre());
        }
        lstProfesores.setModel(modeloLista);
    }

    public void llenarListaEstudiantes() {
        Estudiante estudiante = new Estudiante();
        listaEstudiantes = estudiante.leer();
        DefaultListModel modeloLista = new DefaultListModel();
        for (Estudiante estudianteRecorrido : listaEstudiantes) {
            modeloLista.addElement(estudianteRecorrido.getId() + ": " + estudianteRecorrido.getNombre());
        }
        lstEstudiantes.setModel(modeloLista);
    }

    public void llenarListaCursos() {
        Curso curso = new Curso();
        listaCursos = curso.leer();
        DefaultListModel modeloLista = new DefaultListModel();
        for (Curso cursoRecorrido : listaCursos) {
            modeloLista.addElement(cursoRecorrido.getId() + ": " + cursoRecorrido.getNombre());
        }
        lstCursos.setModel(modeloLista);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnAgregarEstudiante;
    private javax.swing.JButton btnAgregarProfesor;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstCursos;
    private javax.swing.JList<String> lstEstudiantes;
    private javax.swing.JList<String> lstProfesores;
    private javax.swing.JMenuItem mnAsigarProfesor;
    private javax.swing.JMenuItem mnCrearCurso;
    private javax.swing.JMenuItem mnCrearEstudiante;
    private javax.swing.JMenuItem mnCrearProfesor;
    private javax.swing.JMenuItem mnListarCursosDePrf;
    private javax.swing.JMenuItem mnListarEstPorCurso;
    private javax.swing.JMenuItem mnListarEstPorProf;
    private javax.swing.JMenuItem mnListarInfoCurso;
    private javax.swing.JMenuItem mnListarInfoProfesor;
    private javax.swing.JMenuItem mnListarInforEstudiante;
    private javax.swing.JMenuItem mnMatricularEstudiante;
    // End of variables declaration//GEN-END:variables
}
